package ${package}.model;

// Generated 17-set-2009 12.50.53 by Hibernate Tools 3.2.4.GA

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private Long id;
	private String descrizioneItaliano;
	private String descrizioneInglese;
	private String codIso;

	public Language() {
	}

	public Language(Long id) {
		this.id = id;
	}

	public Language(Long id, String descrizioneItaliano,
			String descrizioneInglese, String codIso) {
		this.id = id;
		this.descrizioneItaliano = descrizioneItaliano;
		this.descrizioneInglese = descrizioneInglese;
		this.codIso = codIso;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescrizioneItaliano() {
		return this.descrizioneItaliano;
	}

	public void setDescrizioneItaliano(String descrizioneItaliano) {
		this.descrizioneItaliano = descrizioneItaliano;
	}

	public String getDescrizioneInglese() {
		return this.descrizioneInglese;
	}

	public void setDescrizioneInglese(String descrizioneInglese) {
		this.descrizioneInglese = descrizioneInglese;
	}

	public String getCodIso() {
		return this.codIso;
	}

	public void setCodIso(String codIso) {
		this.codIso = codIso;
	}

}
