package org.regola.model;
// Generated 16-feb-2007 12.58.55 by Hibernate Tools 3.2.0.beta8


import org.cesia.pd.model.J_Ruolo;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DiUtentiruoli generated by hbm2java
 */
@Entity
@Table(name="DI_UTENTIRUOLI"
    , uniqueConstraints = {  }
)
public class RuoliUtente  implements java.io.Serializable {

    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -1477677307583616337L;
	private RuoliUtenteId id;
     private J_Ruolo ruolo;

     // Constructors

    /** default constructor */
    public RuoliUtente() {
    }

    /** full constructor */
    public RuoliUtente(RuoliUtenteId id, J_Ruolo diRuolo) {
       this.id = id;
       this.ruolo = diRuolo;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="logonname", column=@Column(name="LOGONNAME", unique=false, nullable=false, insertable=true, updatable=true, length=100) ), 
        @AttributeOverride(name="ruolo", column=@Column(name="RUOLO", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0) ) } )
    public RuoliUtenteId getId() {
        return this.id;
    }
    
    public void setId(RuoliUtenteId id) {
        this.id = id;
    }
    
    @ManyToOne(cascade={})
    @JoinColumn(name="RUOLO", unique=false, nullable=false, insertable=false, updatable=false)
    public J_Ruolo getRuolo() {
        return this.ruolo;
    }
    
    public void setRuolo(J_Ruolo diRuolo) {
        this.ruolo = diRuolo;
    }
}


