package org.regola.model;
// Generated 16-feb-2007 12.58.55 by Hibernate Tools 3.2.0.beta8


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiUtentiruoliId generated by hbm2java
 */
@Embeddable
public class RuoliUtenteId  implements java.io.Serializable {

    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1645068934606474751L;
	private String logonname;
     private BigDecimal ruolo;

     // Constructors

    /** default constructor */
    public RuoliUtenteId() {
    }

    /** full constructor */
    public RuoliUtenteId(String logonname, BigDecimal ruolo) {
       this.logonname = logonname;
       this.ruolo = ruolo;
    }
   
    // Property accessors

    @Column(name="LOGONNAME", unique=false, nullable=false, insertable=true, updatable=true, length=100)
    public String getLogonname() {
        return this.logonname;
    }
    
    public void setLogonname(String logonname) {
        this.logonname = logonname;
    }

    @Column(name="RUOLO", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0)
    public BigDecimal getRuolo() {
        return this.ruolo;
    }
    
    public void setRuolo(BigDecimal ruolo) {
        this.ruolo = ruolo;
    }


   @Override
public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RuoliUtenteId) ) return false;
		 RuoliUtenteId castOther = ( RuoliUtenteId ) other; 
         
		 return ( (this.getLogonname()==castOther.getLogonname()) || ( this.getLogonname()!=null && castOther.getLogonname()!=null && this.getLogonname().equals(castOther.getLogonname()) ) )
 && ( (this.getRuolo()==castOther.getRuolo()) || ( this.getRuolo()!=null && castOther.getRuolo()!=null && this.getRuolo().equals(castOther.getRuolo()) ) );
   }
   
   @Override
public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogonname() == null ? 0 : this.getLogonname().hashCode() );
         result = 37 * result + ( getRuolo() == null ? 0 : this.getRuolo().hashCode() );
         return result;
   }   


}


