package org.regola.model;
// Generated 16-feb-2007 12.40.23 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DiUtenticontestiprofili generated by hbm2java
 */
@Entity
@Table(name="DI_UTENTICONTESTIPROFILI"
    , uniqueConstraints = {  }
)
public class UtenteContestoProfilo  implements java.io.Serializable {

	private static final long serialVersionUID = -9105463361318490480L;

	private UtenteContestoProfiloId id;
  private Boolean tipoaccesso;

     // Constructors

    /** default constructor */
    public UtenteContestoProfilo() {
    }

	/** minimal constructor */
    public UtenteContestoProfilo(UtenteContestoProfiloId id) {
        this.id = id;
    }
    /** full constructor */
    public UtenteContestoProfilo(UtenteContestoProfiloId id, Boolean tipoaccesso) {
       this.id = id;
       this.tipoaccesso = tipoaccesso;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="logonname", column=@Column(name="LOGONNAME", unique=false, nullable=false, insertable=true, updatable=true, length=100) ), 
        @AttributeOverride(name="idcontesto", column=@Column(name="IDCONTESTO", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0) ), 
        @AttributeOverride(name="idprofilogruppo", column=@Column(name="IDPROFILOGRUPPO", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0) ) } )
    public UtenteContestoProfiloId getId() {
        return this.id;
    }
    
    public void setId(UtenteContestoProfiloId id) {
        this.id = id;
    }
    
    @Column(name="TIPOACCESSO", unique=false, nullable=true, insertable=true, updatable=true, precision=1, scale=0)
    public Boolean getTipoaccesso() {
        return this.tipoaccesso;
    }
    
    public void setTipoaccesso(Boolean tipoaccesso) {
        this.tipoaccesso = tipoaccesso;
    }
}


