package org.regola.model;
// Generated 16-feb-2007 12.40.23 by Hibernate Tools 3.2.0.beta8


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiUtenticontestiprofiliId generated by hbm2java
 */
@Embeddable
public class UtenteContestoProfiloId  implements java.io.Serializable {

	private static final long serialVersionUID = 1714996749582965065L;

	private String logonname;
     private BigDecimal idcontesto;
     private BigDecimal idprofilogruppo;

     // Constructors

    /** default constructor */
    public UtenteContestoProfiloId() {
    }

    /** full constructor */
    public UtenteContestoProfiloId(String logonname, BigDecimal idcontesto, BigDecimal idprofilogruppo) {
       this.logonname = logonname;
       this.idcontesto = idcontesto;
       this.idprofilogruppo = idprofilogruppo;
    }
   
    // Property accessors

    @Column(name="LOGONNAME", unique=false, nullable=false, insertable=true, updatable=true, length=100)
    public String getLogonname() {
        return this.logonname;
    }
    
    public void setLogonname(String logonname) {
        this.logonname = logonname;
    }

    @Column(name="IDCONTESTO", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0)
    public BigDecimal getIdcontesto() {
        return this.idcontesto;
    }
    
    public void setIdcontesto(BigDecimal idcontesto) {
        this.idcontesto = idcontesto;
    }

    @Column(name="IDPROFILOGRUPPO", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0)
    public BigDecimal getIdprofilogruppo() {
        return this.idprofilogruppo;
    }
    
    public void setIdprofilogruppo(BigDecimal idprofilogruppo) {
        this.idprofilogruppo = idprofilogruppo;
    }


   @Override
public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtenteContestoProfiloId) ) return false;
		 UtenteContestoProfiloId castOther = ( UtenteContestoProfiloId ) other; 
         
		 return ( (this.getLogonname()==castOther.getLogonname()) || ( this.getLogonname()!=null && castOther.getLogonname()!=null && this.getLogonname().equals(castOther.getLogonname()) ) )
 && ( (this.getIdcontesto()==castOther.getIdcontesto()) || ( this.getIdcontesto()!=null && castOther.getIdcontesto()!=null && this.getIdcontesto().equals(castOther.getIdcontesto()) ) )
 && ( (this.getIdprofilogruppo()==castOther.getIdprofilogruppo()) || ( this.getIdprofilogruppo()!=null && castOther.getIdprofilogruppo()!=null && this.getIdprofilogruppo().equals(castOther.getIdprofilogruppo()) ) );
   }
   
   @Override
public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogonname() == null ? 0 : this.getLogonname().hashCode() );
         result = 37 * result + ( getIdcontesto() == null ? 0 : this.getIdcontesto().hashCode() );
         result = 37 * result + ( getIdprofilogruppo() == null ? 0 : this.getIdprofilogruppo().hashCode() );
         return result;
   }   


}


